on:
  push:
    branches:
      - bloc
      
name: "Analysis & Build"
jobs:
  build:
    name: Analysis & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/app-release.apk"
#          tag: v1.1.1
#          token: ${{ secrets.TOKEN }}
